global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'producer'
  static_configs:
    - targets: ['producer:9090'] 

- job_name: 'consumer'
  static_configs:
    - targets: ['consumer:9090'] 

- job_name: 'rabbitmq'
  static_configs:
    - targets: ['rabbitmq:15672'] # Assuming RabbitMQ exposes metrics on port 15672

# Add more jobs for other services you want to monitor
